version: '3.2'

services:

  counter_app: &app
    tty: true
    build:
      context: .
      args:
        requirements: requirements/development.txt
    container_name: counter
    environment:
      # use in code
      - DEBUG=True
      - SETTINGS_FILE=api.dev.yml
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - .:/app:delegated
    depends_on:
      - frontend_app
      - postgres
    ports:
      - 8080:8080
      - 8081:8081
    command: make adev

  frontend_app:
    build:
      context: ./frontend/
    volumes:
      - .:/app:delegated
    container_name: counter_front
    ports:
      - 3000:3000

  postgres:
      image: postgres:10
      container_name: counter_postgres
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
      ports:
          - 5432

  test:
    <<: *app
    container_name: counter_test
    ports:
      - 8082:8082
    entrypoint: py.test -v -p no:warnings
    command: ''
