database:
    positive_value: 22
    big_value: 213
    value_inside_a_range: 22
    auto_connect: true
    default_connection: mysql
    connection:
        driver:               'driver' # Required
        host:                 localhost
        username:             'username'
        password:             'password'
        memory:               false
        parameters:           # Required
            name:
                value:                'kirill' # Required